language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++
    - gfortran
    - clang
    - libz-dev
    - libbz2-dev
    - libblas-dev
    - liblapack-dev
    - libarpack2-dev
    - libnetcdf-dev
    - openmpi-bin
    - openmpi-common
    - libopenmpi-dev
    - xutils-dev
    - csh

matrix:
  include:
     - { os: linux, env: PYTHON_VERSION=2.7 }
     - { os: linux, env: PYTHON_VERSION=3.4 }
     - { os: linux, env: PYTHON_VERSION=3.5 } 
     - { os: linux, env: PYTHON_VERSION=3.6 }

sudo: true

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew tap homebrew/science;
      brew update;
      sudo bash scripts/install_gfortran.sh;
    fi

install:
    - source setup_env.sh
    - source install_ambertools.sh

script:
    - tleap -h
    - sqm -h
    - sander --version
    - cpptraj -h
    - python -c "import parmed; print(parmed)"
    - python -c "import sander; print(sander)"
    - python -c "import pytraj; print(pytraj)"
    - python -c "import pdb4amber; print(pdb4amber)"   
    - export AMBERHOME=`python -c "import sys; print(sys.prefix)"`
    - MMPBSA.py --help

after_success:
    - echo "hello there"

notifications:
  email: false
